// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljlgtsjpniegtaxqvrue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqbGd0c2pwbmllZ3RheHF2cnVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzOTE1NTQsImV4cCI6MjA2NTk2NzU1NH0.jv3ImUbCTx9nwETEFDu95P4k51QeEXh4Mhy-vpUwmdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);